project:
  type: website
  output-dir: docs

website:
  title: "From Information to Action: Technical (Science) Communication and Digital Engagement"
  description: "Kairos article, under review"
  page-navigation: true
  other-links: 
    - text: Manuscript PDF
      icon: filetype-pdf
      href: "https://danieljcard1.github.io/card-devasto/article/a11_combined.pdf"
  reader-mode: true
  page-footer:
    left: "under review"
  navbar:
    pinned: true
    right: 
      - icon: github
        href: https://github.com/
        aria-label: Github

  sidebar:
    style: "floating"
    contents: 
      - index.qmd
      - article/a02_background.qmd
      - article/a04_case1.qmd
      - article/a05_case2.qmd
      - article/a06_discussion.qmd
      - article/a07_conclusion.qmd
      - article/a08_references.qmd
     # - article/a11_combined.qmd

format:
  html:
    theme: 
      light: materia
      dark: cyborg
    css: custom.css
    fontsize: 1.2em
    linestretch: 1.7
    grid: 
      sidebar-width: 275px
      body-width: 850px
      margin-width: 260px
      gutter-width: 1.9rem
    toc: true
    toc-depth: 3
    fig-cap-location: top
    tbl-cap-location: top
    lightbox: true
    embed-resources: true #switch to true for final publish?
        
bibliography: references.bib


