---
title: "Introduction"
listing: 
  id: contents
  contents: "article/*.qmd"
  type: table
  table-hover: true
  fields:
    - title
  field-display-names: 
    title: "Section"
  sort: false
  sort-ui: false
  filter-ui: false
---

## Abstract

In this article, we provide a tour of the ecology of emerging digital tools and artifacts that increasingly mediate public engagement in the context of environmental decision making. We draw on two cases of public engagement in which government agencies involve citizens and other stakeholders in decisions where science is relevant. 

In so doing, we shed light on how emerging digital technologies are being used to facilitate 1) collaboration among scientists and other technical experts and 2) engagement with citizen stakeholders. 

As our examination of emerging technologies in this context illustrates, while not all technical communication is science communication, science communication is increasingly also productively viewed as technical communication. We conclude by discussing implications for the relationship between technological literacies, civic action, and sociotechnical deliberation.

## Section Overview

::: {#contents}
:::

## This Webtext

The webtext was built using [Quarto](https://quarto.org/), an open-source scientific and technical publishing system in combination with [RStudio](https://posit.co/download/rstudio-desktop/). 

While we don't have access to the proprietary tools featured in our two cases, Quarto allows us to approximate some of the strategies these tools support.  
